
name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired AWS region

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin your-account-id.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCOUNT_ID: your-account-id

      - name: Build and push Docker image
        run: |
          echo "Building and pushing Docker image..."
          docker build -t your-ecr-repo:latest .
          docker tag your-ecr-repo:latest ${{ steps.login-ecr.outputs.registry }}/your-ecr-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/your-ecr-repo:latest

      - name: Update kubectl configuration
        run: aws eks --region us-east-1 update-kubeconfig --name your-eks-cluster-name

      - name: Deploy to EKS
        run: |
          echo "Deploying to EKS..."
          kubectl apply -f ./k8s

